/*******************************************************************************
** animate.h (animation timings)
*******************************************************************************/

#ifndef ANIMATE_H
#define ANIMATE_H

/* grid object animations */

/* grid object animations should have a frame length that is a  */
/* multiple of 8, as the grid updates to the vbo every 8 frames */

/* the total length of each animation should divide evenly  */
/* into 240 (if the animation loops longer than 240 frames) */

#define ANIM_WATER_FRAME_LENGTH   8
#define ANIM_WATER_NUM_FRAMES     6
#define ANIM_WATER_TOTAL_LENGTH   (ANIM_WATER_FRAME_LENGTH * ANIM_WATER_NUM_FRAMES)

#define ANIM_BRIDGE_COLLAPSING_FRAME_LENGTH   16
#define ANIM_BRIDGE_COLLAPSING_NUM_FRAMES     2
#define ANIM_BRIDGE_COLLAPSING_TOTAL_LENGTH   (ANIM_BRIDGE_COLLAPSING_FRAME_LENGTH * ANIM_BRIDGE_COLLAPSING_NUM_FRAMES)

#define ANIM_PADLOCK_OPENING_FRAME_LENGTH   16
#define ANIM_PADLOCK_OPENING_NUM_FRAMES     4
#define ANIM_PADLOCK_OPENING_TOTAL_LENGTH   (ANIM_PADLOCK_OPENING_FRAME_LENGTH * ANIM_PADLOCK_OPENING_NUM_FRAMES)

#define ANIM_ARROWS_FRAME_LENGTH  8
#define ANIM_ARROWS_NUM_FRAMES    6
#define ANIM_ARROWS_TOTAL_LENGTH  (ANIM_ARROWS_FRAME_LENGTH * ANIM_ARROWS_NUM_FRAMES)

#define ANIM_SPIKES_FRAME_LENGTH  16
#define ANIM_SPIKES_NUM_FRAMES    2
#define ANIM_SPIKES_TOTAL_LENGTH  (ANIM_SPIKES_FRAME_LENGTH * ANIM_SPIKES_NUM_FRAMES)

#define ANIM_PORTCULLIS_OPENING_FRAME_LENGTH  24
#define ANIM_PORTCULLIS_OPENING_NUM_FRAMES    2
#define ANIM_PORTCULLIS_OPENING_TOTAL_LENGTH  (ANIM_PORTCULLIS_OPENING_FRAME_LENGTH * ANIM_PORTCULLIS_OPENING_NUM_FRAMES)

#define ANIM_AUDREY_SPAWNER_FRAME_LENGTH  8
#define ANIM_AUDREY_SPAWNER_NUM_FRAMES    6
#define ANIM_AUDREY_SPAWNER_TOTAL_LENGTH  (ANIM_AUDREY_SPAWNER_FRAME_LENGTH * ANIM_AUDREY_SPAWNER_NUM_FRAMES)

/* thing animations */

/* the total length of each animation should divide evenly  */
/* into 240 (if the animation loops longer than 240 frames) */

#define ANIM_SPELL_SLOW_FRAME_LENGTH  6
#define ANIM_SPELL_SLOW_NUM_FRAMES    8
#define ANIM_SPELL_SLOW_TOTAL_LENGTH  (ANIM_SPELL_SLOW_FRAME_LENGTH * ANIM_SPELL_SLOW_NUM_FRAMES)

#define ANIM_SPELL_FAST_FRAME_LENGTH  3
#define ANIM_SPELL_FAST_NUM_FRAMES    8
#define ANIM_SPELL_FAST_TOTAL_LENGTH  (ANIM_SPELL_FAST_FRAME_LENGTH * ANIM_SPELL_FAST_NUM_FRAMES)

#define ANIM_ICE_CUBE_FRAME_LENGTH  12
#define ANIM_ICE_CUBE_NUM_FRAMES    15
#define ANIM_ICE_CUBE_TOTAL_LENGTH  (ANIM_ICE_CUBE_FRAME_LENGTH * ANIM_ICE_CUBE_NUM_FRAMES)

#define ANIM_PICKUP_FRAME_LENGTH  10
#define ANIM_PICKUP_NUM_FRAMES    4
#define ANIM_PICKUP_TOTAL_LENGTH  (ANIM_PICKUP_FRAME_LENGTH * ANIM_PICKUP_NUM_FRAMES)

#define ANIM_FLASK_FRAME_LENGTH 10
#define ANIM_FLASK_NUM_FRAMES   4
#define ANIM_FLASK_TOTAL_LENGTH (ANIM_FLASK_FRAME_LENGTH * ANIM_FLASK_NUM_FRAMES)

#define ANIM_VAMPIRE_FRAME_LENGTH  10
#define ANIM_VAMPIRE_NUM_FRAMES    4
#define ANIM_VAMPIRE_TOTAL_LENGTH  (ANIM_VAMPIRE_FRAME_LENGTH * ANIM_VAMPIRE_NUM_FRAMES)

#define ANIM_BAT_FRAME_LENGTH 10
#define ANIM_BAT_NUM_FRAMES   4
#define ANIM_BAT_TOTAL_LENGTH (ANIM_BAT_FRAME_LENGTH * ANIM_BAT_NUM_FRAMES)

#define ANIM_PUMPKIN_FRAME_LENGTH 6
#define ANIM_PUMPKIN_NUM_FRAMES   4
#define ANIM_PUMPKIN_TOTAL_LENGTH (ANIM_PUMPKIN_FRAME_LENGTH * ANIM_PUMPKIN_NUM_FRAMES)

#define ANIM_AUDREY_FRAME_LENGTH  12
#define ANIM_AUDREY_NUM_FRAMES    4
#define ANIM_AUDREY_TOTAL_LENGTH  (ANIM_AUDREY_FRAME_LENGTH * ANIM_AUDREY_NUM_FRAMES)

#define ANIM_GHOST_FRAME_LENGTH 12
#define ANIM_GHOST_NUM_FRAMES   4
#define ANIM_GHOST_TOTAL_LENGTH (ANIM_GHOST_FRAME_LENGTH * ANIM_GHOST_NUM_FRAMES)

#define ANIM_SNAKE_FRAME_LENGTH 12
#define ANIM_SNAKE_NUM_FRAMES   4
#define ANIM_SNAKE_TOTAL_LENGTH (ANIM_SNAKE_FRAME_LENGTH * ANIM_SNAKE_NUM_FRAMES)

#define ANIM_SHADE_FRAME_LENGTH 12
#define ANIM_SHADE_NUM_FRAMES   4
#define ANIM_SHADE_TOTAL_LENGTH (ANIM_SHADE_FRAME_LENGTH * ANIM_SHADE_NUM_FRAMES)

#define ANIM_WITCH_FRAME_LENGTH 12
#define ANIM_WITCH_NUM_FRAMES   4
#define ANIM_WITCH_TOTAL_LENGTH (ANIM_WITCH_FRAME_LENGTH * ANIM_WITCH_NUM_FRAMES)

#define ANIM_SORCERESS_FRAME_LENGTH 12
#define ANIM_SORCERESS_NUM_FRAMES   4
#define ANIM_SORCERESS_TOTAL_LENGTH (ANIM_SORCERESS_FRAME_LENGTH * ANIM_SORCERESS_NUM_FRAMES)

#define ANIM_IMP_FRAME_LENGTH  10
#define ANIM_IMP_NUM_FRAMES    4
#define ANIM_IMP_TOTAL_LENGTH  (ANIM_IMP_FRAME_LENGTH * ANIM_IMP_NUM_FRAMES)

#define ANIM_LIL_BOT_FRAME_LENGTH 10
#define ANIM_LIL_BOT_NUM_FRAMES   4
#define ANIM_LIL_BOT_TOTAL_LENGTH (ANIM_LIL_BOT_FRAME_LENGTH * ANIM_LIL_BOT_NUM_FRAMES)

#define ANIM_FAERIE_FRAME_LENGTH  10
#define ANIM_FAERIE_NUM_FRAMES    4
#define ANIM_FAERIE_TOTAL_LENGTH  (ANIM_FAERIE_FRAME_LENGTH * ANIM_FAERIE_NUM_FRAMES)

#define ANIM_WISP_FRAME_LENGTH  10
#define ANIM_WISP_NUM_FRAMES    4
#define ANIM_WISP_TOTAL_LENGTH  (ANIM_WISP_FRAME_LENGTH * ANIM_WISP_NUM_FRAMES)

#define ANIM_KNIGHT_FRAME_LENGTH  10
#define ANIM_KNIGHT_NUM_FRAMES    4
#define ANIM_KNIGHT_TOTAL_LENGTH  (ANIM_KNIGHT_FRAME_LENGTH * ANIM_KNIGHT_NUM_FRAMES)

#define ANIM_MUMMY_MOVING_FRAME_LENGTH  10
#define ANIM_MUMMY_MOVING_NUM_FRAMES    4
#define ANIM_MUMMY_MOVING_TOTAL_LENGTH  (ANIM_MUMMY_MOVING_FRAME_LENGTH * ANIM_MUMMY_MOVING_NUM_FRAMES)

#define ANIM_MUMMY_COLLAPSE_FRAME_LENGTH  10
#define ANIM_MUMMY_COLLAPSE_NUM_FRAMES    3
#define ANIM_MUMMY_COLLAPSE_TOTAL_LENGTH  (ANIM_MUMMY_COLLAPSE_FRAME_LENGTH * ANIM_MUMMY_COLLAPSE_NUM_FRAMES)

#define ANIM_JIANGSHI_MOVING_FRAME_LENGTH  10
#define ANIM_JIANGSHI_MOVING_NUM_FRAMES    4
#define ANIM_JIANGSHI_MOVING_TOTAL_LENGTH  (ANIM_JIANGSHI_MOVING_FRAME_LENGTH * ANIM_JIANGSHI_MOVING_NUM_FRAMES)

#define ANIM_JIANGSHI_STOP_FRAME_LENGTH   10
#define ANIM_JIANGSHI_STOP_NUM_FRAMES     3
#define ANIM_JIANGSHI_STOP_TOTAL_LENGTH   (ANIM_JIANGSHI_STOP_FRAME_LENGTH * ANIM_JIANGSHI_STOP_NUM_FRAMES)

#define ANIM_PUFF_FRAME_LENGTH  4
#define ANIM_PUFF_NUM_FRAMES    3
#define ANIM_PUFF_TOTAL_LENGTH  (ANIM_PUFF_FRAME_LENGTH * ANIM_PUFF_NUM_FRAMES)

/* menu animations */
#define ANIM_MENU_CURSOR_BLINK_FRAME_LENGTH   15
#define ANIM_MENU_CURSOR_BLINK_NUM_FRAMES     2
#define ANIM_MENU_CURSOR_BLINK_TOTAL_LENGTH   (ANIM_MENU_CURSOR_BLINK_FRAME_LENGTH * ANIM_MENU_CURSOR_BLINK_NUM_FRAMES)

#define ANIM_MENU_PAGE_ARROW_FRAME_LENGTH     15
#define ANIM_MENU_PAGE_ARROW_NUM_FRAMES       2
#define ANIM_MENU_PAGE_ARROW_TOTAL_LENGTH     (ANIM_MENU_PAGE_ARROW_FRAME_LENGTH * ANIM_MENU_PAGE_ARROW_NUM_FRAMES)

/* macro for determining current animation frame */
#define ANIM_CURRENT_FRAME(name)                                               \
  ((adjusted_timer_count % ANIM_##name##_TOTAL_LENGTH) / ANIM_##name##_FRAME_LENGTH)

#define ANIM_ICE_FRAME(name)                                                   \
  ((freeze_timer_count % ANIM_##name##_TOTAL_LENGTH) / ANIM_##name##_FRAME_LENGTH)

#define ANIM_GLOBAL_FRAME(name)                                                \
  ((G_timer_count % ANIM_##name##_TOTAL_LENGTH) / ANIM_##name##_FRAME_LENGTH)

#endif
